# -*- mode: ruby -*-
#vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '2048' # 2GB of memory for vm
  end

  config.vm.provision 'shell', path: './cross-compiler.sh'
end
